spring:
  # For file-based configuration
  config:
    import:
      optional:configserver:http://localhost:8071/
  application:
    name: groshik
  profiles:
    active: dev
#  cloud:
#    config:
#      token: myroot

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

management:
  endpoints:
    web:
      base-path: /
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    db:
      enabled: false
    diskspace:
      enabled: true